### ISSUE TITLE
'XCDYouTubeKit.h' file not found with <angled> include; use "quotes" instead

### ISSUE THREAD

**Issue by zwacky** [abomadi/CordovaYoutubeVideoPlayer#1]
Hey there, thank you for your fork!

Just wanted to point out that when I started using your fork I stepped on this small issue (where I just followed what it said in the title). P.s. I have I haven't touched any iOS native development yet.

YoutubeVideoPlayer.m
```
#import "YoutubeVideoPlayer.h"
#import <XCDYouTubeKit.h>
#import "AVFoundation/AVFoundation.h"
#import <AVKit/AVKit.h>
```

**Comment by abomadi** [comment]
@zwacky thanks i have merged your patch.

**Comment by giuseeFG** [comment]
just add pod "XCDYouTubeKit", "~> 2.8" in Podfile and then pod update
